export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REDUCE_INGREDIENT = "REDUCE_INGREDIENT";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
